### PR TITLE
43 add parameter for saving single subject cis when batch generating cis

### PR DESCRIPTION
**Pull request by aucuparia**
Didn't have a dataset at hand with which to properly test this. Please actually test this with some data before merging.

### CODE REVIEW

**Comment by rdotsch** [comment]
I tested this with this [data set](https://github.com/rdotsch/rcicr/files/1190178/rcicrdemo.csv.zip), using the following code:

```R # Regenerate rdata file
rcicr::generateStimuli2IFC(list(mnes='MNES.JPG'), n_trials = 100, save_as_png = F)

# Load response data
responsedata <- read.csv('rcicrdemo.csv')

# Compute CIs
cis <- rcicr::generateCI(
  stimuli = responsedata$stimulus, 
  responses = responsedata$response, 
  baseimage = "mnes", 
  rdata = 'stimuli/rcic_seed_1_time_Aug_01_2017_11_46.Rdata',  ### UPDATE THIS PATH ###
  participants = responsedata$subject, 
  save_individual_cis = T)
```

It gives me the following output and error:

```starting worker pid=5842 on localhost:11640 at 11:48:42.261
starting worker pid=5850 on localhost:11640 at 11:48:42.584
starting worker pid=5858 on localhost:11640 at 11:48:42.924
starting worker pid=5866 on localhost:11640 at 11:48:43.271
Loading required package: rcicr
Loading required package: rcicr
Loading required package: rcicr
Loading required package: rcicr
loaded rcicr and set parent environment
loaded rcicr and set parent environment
loaded rcicr and set parent environment
loaded rcicr and set parent environment
  |==========================================================================================================| 100%
 Show Traceback
 
 Rerun with Debug
 Error in { : 
  task 1 failed - "argument "filename" is missing, with no default"
```

With this traceback:

```
Error in { : 
  task 1 failed - "argument "filename" is missing, with no default" 
4.
stop(simpleError(msg, call = expr)) 
3.
e$fun(obj, substitute(ex), parent.frame(), e$data) 
2.
foreach::foreach(obs = 1:npids, .combine = "c", .packages = "rcicr") %dopar% 
    {
        setTxtProgressBar(pb, obs)
        pid.rows <- pids == obs ... at generateCI.R#143
1.
generateCI(stimuli = responsedata$stimulus, responses = responsedata$response, 
    baseimage = "mnes", rdata = rdata, participants = responsedata$subject, 
    save_individual_cis = T) 
```

**Comment by rdotsch** [comment]
See discussion at #87 before proceeding.

**Comment by aucuparia** [comment]
@rdotsch I see. My plan is to finish this issue first (because it is a substantial refactor of the code), get that approved by you and merged into dev, then start with #87.

Agreed?

**Comment by rdotsch** [comment]
Agreed!

**Comment by aucuparia** [comment]
I've pushed a bugfix commit. Your script should now work. Could you verify, check if the output is okay, and merge?

**Comment by rdotsch** [comment]
Works perfectly!

**Pull request merged**
